development:
  adapter: postgresql
  encoding: utf8
  database: avlog_development
  host: localhost
  username: joseadriano
  password:
  # username: postgres
  # password: postgres
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: avlog_test
  host: localhost
  username: joseadriano
  password:
  # username: postgres
  # password: postgres
  pool: 5
  port: 5432

# production:
#   adapter: postgresql
#   encoding: utf8
#   database: atlas
#   host: atlas-production.cszxzs90kw7x.us-east-1.rds.amazonaws.com
#   username: equipenel
#   password: uXv5NCrkYQqawu2V
#   pool: 5
#   port: 5432
#
# staging:
#   adapter: postgresql
#   encoding: utf8
#   database: atlas_staging
#   host: atlas-production.cszxzs90kw7x.us-east-1.rds.amazonaws.com
#   username: equipenel
#   password: uXv5NCrkYQqawu2V
#   pool: 5
#   port: 5432
